Sub exporttojson
'First export to CSV which we will later use as the source for the export to json
Dim Propval(1) as New com.sun.star.beans.PropertyValue
Propval(0).Name = "FilterName"
Propval(0).Value = "Text - txt - csv (StarCalc)"
Propval(1).Name = "FilterOptions"
Propval(1).Value ="94,34,0,1,1"
Doc = ThisComponent
Dim FileName as String
FileName = Doc.getURL()
splitName = split(FileName, ".")
FileName = splitName(0) + ".csv"
Doc.StoreToURL(FileName, Propval())

'Export to JSON

'Get the number of keys in the header of the csv
Dim csv As Integer
Dim klen As Integer
csv = FreeFile
Open FileName For Input As csv
Line Input #csv, first
keys = split(first, "^")
klen = 0
For Each i in keys
	klen = klen + 1
Next i

'Need to count the number of lines in the csv (after header line)
Dim lines as Integer
lines = 0
Do While not eof(csv)
	Line Input #csv, line   
	If line <>"" Then
		lines = lines + 1
	End If
Loop
Close #csv

'Need to re-open the csv again for a fresh read from just after the header
Open FileName For Input As csv
Line Input #csv, line

'Open each JSON file for writing
Dim json As Integer
Dim CurrentLine As String
Dim fn As String
Dim temp As Integer
Dim asteriskcounter As Integer

For line = 0 to lines-1
	Line Input #csv, CurrentLine   
	If CurrentLine <>"" Then
    	values = split(CurrentLine, "^")
		fn = splitName(0) + "." + Replace(Replace(values(0),"*","_"),"/","_") + ".json" 
		json = Freefile
		Open fn For Output As json
		Print #json, "{"	
		Print #json, "  ""properties"" : ["
		Print #json, "    {"
		Print #json, "      ""id"" : 35350372,"
		Print #json, "      ""parentId"" : null,"
		Print #json, "      ""type"" : ""tab-section"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""value"" : ""Combat"","
		Print #json, "      ""rank"" : -14,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350373,"
		Print #json, "      ""parentId"" : 35350397,"
		Print #json, "      ""type"" : ""message"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""Primary Attack"","
		Print #json, "      ""icon"" : ""/images/message.png"","
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : -11,"
		Print #json, "      ""message"" : ""Primary Attack {primary_name} To Hit: {1d20 + primary_bonus+attack_bonus+special_attack_bonus}, Damage: {1d@:primary_damage:+primary_bonus}"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350374,"
		Print #json, "      ""parentId"" : null,"
		Print #json, "      ""type"" : ""tab-section"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""value"" : ""Monster"","
		Print #json, "      ""rank"" : -15,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350386,"
		Print #json, "      ""parentId"" : 35350374,"
		Print #json, "      ""type"" : ""title-section"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""collapsed"" : false"
		Print #json, "      },"
		Print #json, "      ""value"" : ""Info"","
		Print #json, "      ""rank"" : -23,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350392,"
		Print #json, "      ""parentId"" : 35350403,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""hit_points-maximum"","
		Print #json, "      ""value"" : 10,"
		Print #json, "      ""rank"" : 102,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350393,"
		Print #json, "      ""parentId"" : 35350403,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""hit_points-temporary"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 104,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350394,"
		Print #json, "      ""parentId"" : 35350374,"
		Print #json, "      ""type"" : ""title-section"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""collapsed"" : false"
		Print #json, "      },"
		Print #json, "      ""value"" : ""Saving Throws (Save As...)"","
		Print #json, "      ""rank"" : -20,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350396,"
		Print #json, "      ""parentId"" : 35350374,"
		Print #json, "      ""type"" : ""title-section"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""collapsed"" : true"
		Print #json, "      },"
		Print #json, "      ""private"" : true,"
		Print #json, "      ""value"" : ""Hidden"","
		Print #json, "      ""rank"" : -5,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350400,"
		Print #json, "      ""parentId"" : 35350397,"
		Print #json, "      ""type"" : ""message"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""Secondary Attack"","
		Print #json, "      ""icon"" : ""/images/message.png"","
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : -8,"
		Print #json, "      ""message"" : ""Secondary Attack {secondary_name} To Hit: {1d20 + secondary_bonus+attack_bonus+special_attack_bonus}, Damage: {1d@:secondary_damage:+secondary_bonus}"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350403,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""health"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""Hit Points"","
		Print #json, "      ""value"" : 10,"
		Print #json, "      ""rank"" : 111,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350404,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""appearance"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""appearances"" : []"
		Print #json, "      },"
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : 112,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350406,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""Initiative"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 88,"
		Print #json, "      ""message"" : ""!r initiative = 1d6"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350430,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""text"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Primary Name"","
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : -5,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350431,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Primary Bonus"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : -4,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350432,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""text"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Primary Damage"","
		Print #json, "      ""value"" : ""0"","
 		Print #json, "      ""rank"" : -3,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350433,"
		Print #json, "      ""parentId"" : 35350429,"
		Print #json, "      ""type"" : ""table"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""headers"" : ["
		Print #json, "          ""W Label"","
		Print #json, "          ""Weapon"","
		Print #json, "          ""Hit Bonus"","
		Print #json, "          ""Damage"""
		Print #json, "        ]"
		Print #json, "      },"
		Print #json, "      ""rank"" : -1,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350434,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""heading"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""value"" : ""Pri. Attack"","
		Print #json, "      ""rank"" : -6,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350435,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""heading"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""value"" : ""Sec. Attack"","
		Print #json, "      ""rank"" : -2,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350436,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""text"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Secondary Name"","
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : -1,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350437,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Secondary Bonus"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 0,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350438,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""text"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Secondary Damage"","
		Print #json, "      ""value"" : ""0"","
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350439,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""heading"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""value"" : ""Other Attacks"","
		Print #json, "      ""rank"" : 7,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350464,"
		Print #json, "      ""parentId"" : 35350396,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Race Death Ray or Poison"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 0,"
		Print #json, "      ""formula"" : ""if(indexOf(\""Dwarf\"",Race)==0,-4,if(indexOf(\""Halfling\"",Race)==0,-4,0))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350465,"
		Print #json, "      ""parentId"" : 35350396,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Race Magic Wands"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""formula"" : ""if(indexOf(\""Dwarf\"",Race)==0,-4,if(indexOf(\""Halfling\"",Race)==0,-4,if(indexOf(\""Elf\"",Race)==0,-2,0)))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350466,"
		Print #json, "      ""parentId"" : 35350396,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Race Paralysis or Turn to Stone"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 2,"
		Print #json, "      ""formula"" : ""if(indexOf(\""Dwarf\"",Race)==0,-4,if(indexOf(\""Halfling\"",Race)==0,-4,if(indexOf(\""Elf\"",Race)==0,-1,0)))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350467,"
		Print #json, "      ""parentId"" : 35350396,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Race Dragon Breath"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 3,"
		Print #json, "      ""formula"" : ""if(indexOf(\""Dwarf\"",Race)==0,-3,if(indexOf(\""Halfling\"",Race)==0,-3,0))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350468,"
		Print #json, "      ""parentId"" : 35350396,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Race Rod Staff or Spell"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 4,"
		Print #json, "      ""formula"" : ""if(indexOf(\""Dwarf\"",Race)==0,-4,if(indexOf(\""Halfling\"",Race)==0,-4,if(indexOf(\""Elf\"",Race)==0,-2,0)))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350486,"
		Print #json, "      ""parentId"" : 35350396,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Turned Roll"","
		Print #json, "      ""value"" : 20,"
		Print #json, "      ""rank"" : 5,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350497,"
		Print #json, "      ""parentId"" : 35350374,"
		Print #json, "      ""type"" : ""title-section"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""collapsed"" : false"
		Print #json, "      },"
		Print #json, "      ""value"" : ""Spells"","
		Print #json, "      ""rank"" : -11,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350498,"
		Print #json, "      ""parentId"" : 35350497,"
		Print #json, "      ""type"" : ""table"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""headers"" : ["
		Print #json, "          ""Lv1"","
		Print #json, "          ""Lv2"","
		Print #json, "          ""Lv3"","
		Print #json, "          ""Lv4"","
		Print #json, "          ""Lv5"","
		Print #json, "          ""Lv6"""
		Print #json, "        ]"
		Print #json, "      },"
		Print #json, "      ""rank"" : 0,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350499,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""spell_two"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 0,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350504,"
		Print #json, "      ""parentId"" : 35350503,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""slots_lv_1-max"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""formula"" : ""spell_one"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350503,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""checkboxes"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Slots Lv 1"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 5,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350509,"
		Print #json, "      ""parentId"" : 35350374,"
		Print #json, "      ""type"" : ""text"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""BFRPG Monster Template by Brucifer - version"","
		Print #json, "      ""value"" : ""1.2"","
		Print #json, "      ""rank"" : -4,"
		Print #json, "      ""formula"" : ""1.2"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350510,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""checkboxes"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Slots Lv 2"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 6,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350511,"
		Print #json, "      ""parentId"" : 35350510,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""slots_lv_2-max"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""formula"" : ""spell_two"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350512,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""checkboxes"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Slots Lv 3"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 7,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350513,"
		Print #json, "      ""parentId"" : 35350512,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""slots_lv_3-max"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""formula"" : ""spell_threes"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350514,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""checkboxes"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Slots Lv 4"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 8,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350515,"
		Print #json, "      ""parentId"" : 35350514,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""slots_lv_4-max"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""formula"" : ""spell_fours"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350516,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""checkboxes"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Slots Lv 5"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 9,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350517,"
		Print #json, "      ""parentId"" : 35350516,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""slots_lv_5-max"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""formula"" : ""spell_fives"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350518,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""checkboxes"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Slots Lv 6"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 10,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350519,"
		Print #json, "      ""parentId"" : 35350518,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""slots_lv_6-max"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""formula"" : ""spell_sixes"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350520,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""spell_one"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : -3,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350525,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""spell_fours"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 2,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350528,"
		Print #json, "      ""parentId"" : 35350497,"
		Print #json, "      ""type"" : ""heading"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""value"" : ""Spell Book"","
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350529,"
		Print #json, "      ""parentId"" : 35350497,"
		Print #json, "      ""type"" : ""paragraph"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""value"" : ""<p>&nbsp;</p>"","
		Print #json, "      ""rank"" : 2,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350397,"
		Print #json, "      ""parentId"" : 35350372,"
		Print #json, "      ""type"" : ""filter-list"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : -19,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350402,"
		Print #json, "      ""parentId"" : 35350397,"
		Print #json, "      ""type"" : ""message"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""Tertiary Attack"","
		Print #json, "      ""icon"" : ""/images/message.png"","
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : -6,"
		Print #json, "      ""message"" : ""Tertiary Attack {tertiary_name} To Hit: {1d20 + tertiary_bonus+attack_bonus+special_attack_bonus}, Damage: {1d@:tertiary_damage:+tertiary_bonus}"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350429,"
		Print #json, "      ""parentId"" : 35350374,"
		Print #json, "      ""type"" : ""title-section"","
		Print #json, "      ""data"" : {"
		Print #json, "        ""collapsed"" : false"
		Print #json, "      },"
		Print #json, "      ""value"" : ""Attacks"","
		Print #json, "      ""rank"" : -21,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350391,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : {},"
		Print #json, "      ""name"" : ""Attack Bonus"","
		Print #json, "      ""value"" : 1,"
		Print #json, "      ""rank"" : 85,"
		Print #json, "      ""formula"" : ""if(hit_dice<=32,round(-0.0000009494*(hit_dice^5)+0.0000800727*(hit_dice^4)-0.0017979765*(hit_dice^3)-0.0135376213*(hit_dice^2)+1.1403068696*hit_dice+(-0.1193966271)),16)"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350415,"
		Print #json, "      ""parentId"" : 35350394,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Dragon Breath"","
		Print #json, "      ""value"" : 15,"
		Print #json, "      ""rank"" : 3,"
		Print #json, "      ""message"" : ""Dragon Breath Saving Throw: {1d20 >= dragon_breath}"","
		Print #json, "      ""formula"" : ""if(indexOf(\""Cleric\"",class)==0,race_dragon_breath+(-race_paralysis_or_turn_to_stone)+paralysis_or_turn_to_stone+2,if(indexOf(\""Fighter\"",class)==0,race_dragon_breath+if(level<=20,round(-0.0000002026*(level^8)+0.0000152076*(level^7)-0.000456995*(level^6)+0.0069861521*(level^5)-0.0566859839*(level^4)+0.2266792207*(level^3)-0.3211940758*(level^2)-0.4657900132*level+15.917346511),9),if(indexOf(\""Thief\"",class)>=0,race_dragon_breath+if(level<=20,round(-0.0000118455*(level^5)+0.0006218872*(level^4)-0.0119908467*(level^3)+0.1034594158*(level^2)-0.8839160048*level+16.7083591331),6),if(indexOf(\""Magic-User\"",class)==0,race_dragon_breath+if(level<=20,round(-0.0000059227*(level^5)+0.0003619313*(level^4)-0.0081369082*(level^3)+0.0814198656*(level^2)-0.5932539067*level+16.3118679051),11),20))))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350416,"
		Print #json, "      ""parentId"" : 35350394,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Rod Staff or Spell"","
		Print #json, "      ""value"" : 17,"
		Print #json, "      ""rank"" : 4,"
		Print #json, "      ""message"" : ""Rod Staff or Spell Saving Throw: {1d20 >= rod_staff_or_spell}"","
		Print #json, "      ""formula"" : ""if(indexOf(\""Cleric\"",class)==0,race_rod_staff_or_spell+(-race_dragon_breath)+dragon_breath+(-1),if(indexOf(\""Magic-User\"",class)>=0,race_dragon_breath+if(level<=20,round(-0.000000412*(level^8)+0.0000330605*(level^7)-0.0010844267*(level^6)+0.018701251*(level^5)-0.1813672488*(level^4)+0.9782723775*(level^3)-2.6968326665*(level^2)+2.7194618752*level+14.1215946654),8),if(indexOf(\""Fighter\"",class)==0,race_rod_staff_or_spell+(-race_magic_wands)+magic_wand+4,if(indexOf(\""Thief\"",class)==0,race_rod_staff_or_spell+(-race_death_ray_or_poison)+death_ray_or_poison+2,20))))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350488,"
		Print #json, "      ""parentId"" : 35350394,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Magic Wands"","
		Print #json, "      ""value"" : 13,"
		Print #json, "      ""rank"" : 1,"
		Print #json, "      ""message"" : ""Magic Wands Saving Throw: {1d20 >= magic_wands}"","
		Print #json, "      ""formula"" : ""if(indexOf(\""Cleric\"",class)==0,race_magic_wands+if(level<=20,round(-0.0000013274*(level^6)+0.0000559631*(level^5)-0.0004940474*(level^4)-0.0079683478*(level^3)+0.1630964222*(level^2)-1.1700438434*level+12.9583591331),6),if(indexOf(\""Fighter\"",class)==0,race_magic_wands+if(level<=19,round(-0.0000002989*(level^8)+0.0000232422*(level^7)-0.0007310049*(level^6)+0.0118833669*(level^5)-0.1053258172*(level^4)+0.4855565021*(level^3)-0.933699521*(level^2)-0.3398406655*level+13.9684975507),6),if(indexOf(\""Magic-User\"",class)==0,race_magic_wands+if(level<=20,round(0.0000350653*(level^5)-0.002040162*(level^4)+0.0425793573*(level^3)-0.3820818904*(level^2)+0.9587124414*level+13.3690402477),6),if(indexOf(\""Thief\"",class)==0,race_magic_wands+if(level<=11,round(-0.2363636364*level+14.3272727273),if(level<=20,round(-0.2333333333*level+13.0666666667),8)),20))))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350521,"
		Print #json, "      ""parentId"" : 35350394,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Paralysis or Turn to Stone"","
		Print #json, "      ""value"" : 14,"
		Print #json, "      ""rank"" : 2,"
		Print #json, "      ""message"" : ""Paralysis or Turn to Stone Saving Throw: {1d20 >= paralysis_or_turn_to_stone}"","
		Print #json, "      ""formula"" : ""if(indexOf(\""Magic-User\"",class)>=0,race_paralysis_or_turn_to_stone+if(level<=20,round(0.0000350653*(level^5)-0.002040162*(level^4)+0.0425793573*(level^3)-0.3820818904*(level^2)+0.9587124414*level+12.3690402477),5),if(indexOf(\""Cleric\"",class)==0,race_paralysis_or_turn_to_stone+if(level<=20,round(0.0000049506*(level^6)-0.0003178086*(level^5)+0.0078912969*(level^4)-0.0951341589*(level^3)+0.5702836128*(level^2)-1.7858108966*level+15.1999999999),9)if(indexOf(\""Fighter\"",class)==0,race_paralysis_or_turn_to_stone+if(level<=18,round(0.0000002098*(level^8)-0.0000163739*(level^7)+0.00052028*(level^6)-0.0086445844*(level^5)+0.0801484297*(level^4)-0.4087726145*(level^3)+1.0531792976*(level^2)-1.4786400703*level+14.941551316),8),if(indexOf(\""Thief\"",class)==0,race_paralysis_or_turn_to_stone+if(level<=20,round(-0.0000059227*(level^5)+0.0003619313*(level^4)-0.0081369082*(level^3)+0.0814198656*(level^2)-0.5932539067*level+13.3118679051),8),20))))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350500,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""spell_threes"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 0,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350501,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""spell_fives"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 3,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350502,"
		Print #json, "      ""parentId"" : 35350498,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""spell_sixes"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 4,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35350526,"
		Print #json, "      ""parentId"" : 35350394,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Death Ray or Poison"","
		Print #json, "      ""value"" : 12,"
		Print #json, "      ""rank"" : 0,"
		Print #json, "      ""message"" : ""Death Ray or Poison Saving Throw: {1d20 >= death_ray_or_poison}"","
		Print #json, "      ""formula"" : ""if(indexOf(\""Cleric\"",class)==0,race_death_ray_or_poison +if(level<=20,round(-0.0000013274*(level^6)+0.0000559631*(level^5)-0.0004940474*(level^4)-0.0079683478*(level^3)+0.1630964222*(level^2)-1.1700438434*level+11.9583591331),5),if(indexOf(\""Fighter\"",class)==0,race_death_ray_or_poison+if(level<=20,round(-0.0000009718*(level^7)+0.0000692796*(level^6)-0.0019822859*(level^5)+0.0290491553*(level^4)-0.2298498615*(level^3)+0.942984472*(level^2)-2.0522592504*level+13.0568668058),5),if(indexOf(\""Thief\"",class)>=0,race_death_ray_or_poison+if(level<=20,round(-0.000000412*(level^8)+0.0000330605*(level^7)-0.0010844267*(level^6)+0.018701251*(level^5)-0.1813672488*(level^4)+0.9782723775*(level^3)-2.6968326665*(level^2)+2.7194618752*level+12.1215946654),6),if(indexOf(\""Magic-User\"",class)==0,race_death_ray_or_poison+if(level<=20,round(-0.0000059227*(level^5)+0.0002599559*(level^4)-0.0038539385*(level^3)+0.0220395502*(level^2)-0.2906620982*level+13.3964912281),8),20))))"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35381829,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""checkbox"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Silver Weapons to Hit"","
		Print #json, "      ""value"" : false,"
		Print #json, "      ""rank"" : 81,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35381830,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Unarmored Armor Class"","
		Print #json, "      ""rank"" : 80,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35381832,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""text"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Special Weapons to Hit"","
		Print #json, "      ""rank"" : 83,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35381834,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""XP Value"","
		Print #json, "      ""value"" : 25,"
		Print #json, "      ""rank"" : 114,"
		Print #json, "      ""formula"" : ""(if(hit_dice<=9,round(0.0003100198*(hit_dice^8)-0.0159751401*(hit_dice^7)+0.3070363562*(hit_dice^6)-2.9492034312*(hit_dice^5)+15.5146803505*(hit_dice^4)-45.0840403449*(hit_dice^3)+79.912701777*(hit_dice^2)-32.7132759386*hit_dice+10.0027766351),if(hit_dice<=18,round(0.0248043023*(hit_dice^8)-2.7433597717*(hit_dice^7)+132.0981682046*(hit_dice^6)-3617.0083876119*(hit_dice^5)+61596.1462484374*(hit_dice^4)-668037.0863365*(hit_dice^3)+4505883.20923982*(hit_dice^2)-17280396.2254241*hit_dice+28848403.228295),750*hit_dice+(-9750))))+special_ability_bonus*(if(hit_dice<=0,3,if(hit_dice<=9,round(-0.0045386905*(hit_dice^8)+0.1887896827*(hit_dice^7)-3.2975694473*(hit_dice^6)+31.3986111372*(hit_dice^5)-176.9585070864*(hit_dice^4)+599.1256949074*(hit_dice^3)-1176.7393857958*(hit_dice^2)+1215.2869056248*hit_dice+(-477.0000003323)),if(hit_dice<=18,round(-0.004960922*(hit_dice^8)+0.5605836115*(hit_dice^7)-27.5658032157*(hit_dice^6)+770.3484967893*(hit_dice^5)-13380.1189721578*(hit_dice^4)+147891.323660656*(hit_dice^3)-1015761.76531175*(hit_dice^2)+3963231.61255838*hit_dice+(-6724973.91269515)),25*hit_dice+(-300)))))\n"","
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35397636,"
		Print #json, "      ""parentId"" : 35350386,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Special Attack Bonus"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 86,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35397639,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""heading"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""value"" : ""Ter. Attack"","
		Print #json, "      ""rank"" : 2,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35398166,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Tertiary Bonus"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 5,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35398167,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""number"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Tertiary Damage"","
		Print #json, "      ""value"" : 0,"
		Print #json, "      ""rank"" : 6,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
		Print #json, "    {"
		Print #json, "      ""id"" : 35402236,"
		Print #json, "      ""parentId"" : 35350433,"
		Print #json, "      ""type"" : ""text"","
		Print #json, "      ""data"" : null,"
		Print #json, "      ""name"" : ""Tertiary Name"","
		Print #json, "      ""value"" : """","
		Print #json, "      ""rank"" : 4,"
		Print #json, "      ""characterId"" : 673402"
		Print #json, "    },"
	    	
    	'Find the last non-empty or non-zero line for each entry
    	lastValidLine = 0
    	For j = 0 to klen-1
    		If values(j) = "" OR values(j) = "0" Then
    			'NOT
    		Else
    			lastValidLine = j
    		End If
    	Next j
    		
    	For i = 0 To klen-1
    		keyValString = "        {" & CHR(34) & LCase(keys(i)) & CHR(34) & ": " & CHR(34) & values(i) & CHR(34) & " !!!!!!!!!!!!!!!!!!!!!!! },"
    		keyValLastEntry = "        {" & CHR(34) & LCase(keys(i)) & CHR(34) & ": " & CHR(34) & values(i) & CHR(34) & " !!!!!!!!!!!!!!!!!!!!!!! }"
    		
    		Select Case keys(i)
    		
    		Case "Monster":
				Print #json,"    {"
				Print #json,"      ""id"" : 35381831,"
				Print #json,"      ""parentId"" : 35350386,"
				Print #json,"      ""type"" : ""checkbox"","
				Print #json,"      ""data"" : null,"
				Print #json,"      ""name"" : ""Magic Weapons to Hit"","
				If InStr(1,values(i),"*") > 0 Then
					Print #json,"      ""value"": true,"
				Else
					Print #json,"      ""value"" : false,"
				End If
				Print #json,"      ""rank"" : 82,"
				Print #json,"      ""characterId"" : 673402"
				Print #json,"    },"

			Case "AC":
				Print #json,"    {"
				Print #json,"      ""id"": 35350390,"
				Print #json,"      ""parentId"": 35350386,"
				Print #json,"      ""type"": ""number"","
				Print #json,"      ""data"": {},"
				Print #json,"      ""name"": ""Armor Class"","
				Print #json,"      ""value"": " & values(i) & ","
				Print #json,"      ""rank"": 79,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"

			Case "Hit Dice":
				asteriskcounter = 0
				temp = 0
				While (temp + 1 > 0)
					temp = InStr(temp + 1,values(i),"*")
					If temp > 1 Then asteriskcounter = asteriskcounter + 1 Else temp = -1
				Wend
				Print #json,"    {"
				Print #json,"      ""id"": 35350505,"
				Print #json,"      ""parentId"": 35350386,"
				Print #json,"      ""type"": ""number"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""name"": ""Hit Dice"","
				If (asteriskcounter > 0) Then
					Print #json,"      ""value"": " & Left(values(i),InStr(1,values(i),"*")-1) & ","				
				Else
					Print #json,"      ""value"": " & values(i) & ","
				End If
				Print #json,"      ""rank"": 103,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"
				Print #json,"    {"
				Print #json,"      ""id"" : 35381833,"
				Print #json,"      ""parentId"" : 35350386,"
				Print #json,"      ""type"" : ""number"","
				Print #json,"      ""data"" : null,"
				Print #json,"      ""name"" : ""Special Ability Bonus"","
				Print #json,"      ""value"" : " & asteriskcounter & ","
				Print #json,"      ""rank"" : 113,"
				Print #json,"      ""characterId"" : 673402"
				Print #json,"    },"

    		Case "Hit Dice Modifier":
				Print #json,"    {"
				Print #json,"      ""id"": 35350508,"
				Print #json,"      ""parentId"": 35350386,"
				Print #json,"      ""type"": ""number"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""name"": ""Hit Dice Bonus"","
				Print #json,"      ""value"": " & values(i) & ","
				Print #json,"      ""rank"": 106,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"
							    		
    		Case "Movement":
				Print #json,"    {"
				Print #json,"      ""id"": 35397637,"
				Print #json,"      ""parentId"": 35350386,"
				Print #json,"      ""type"": ""text"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""name"": ""Movement"","
				Print #json,"      ""value"": """ & values(i) & ""","
				Print #json,"      ""rank"": 115,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"

			Case "Attacks":
				Print #json,"    {"
				Print #json,"      ""id"": 35350440,"
				Print #json,"      ""parentId"": 35350433,"
				Print #json,"      ""type"": ""paragraph"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""value"": ""<h4>" & values(i) & "&nbsp;</h4>"","
				Print #json,"      ""rank"": 8,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"

    		Case "Damage":
				Print #json,"    {"
				Print #json,"      ""id"": 35350441,"
				Print #json,"      ""parentId"": 35350433,"
				Print #json,"      ""type"": ""paragraph"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""value"": ""<h4>" & values(i) & "&nbsp;</h4>"","
				Print #json,"      ""rank"": 10,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"    		

    		Case "Special Damage":
				Print #json,"    {"
				Print #json,"      ""id"": 35350442,"
				Print #json,"      ""parentId"": 35350433,"
				Print #json,"      ""type"": ""paragraph"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""value"": ""<h4>" & values(i) & "&nbsp;</h4>"","
				Print #json,"      ""rank"": 9,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"

    		Case "Number appearing":
				temp = 0 ' Do nothing

			Case "Save As":
				Print #json,"    {"
				Print #json,"      ""id"": 35350388,"
				Print #json,"      ""parentId"": 35350394,"
				Print #json,"      ""type"": ""text"","
				Print #json,"      ""data"": {},"
				Print #json,"      ""name"": ""Class"","
				If val(right(values(i),2)) = 0 Then
					Print #json,"      ""value"": """ & values(i) & ""","
				Else
					Print #json,"      ""value"": """ & trim(left(values(i),len(values(i))-2)) & ""","
				End If
				Print #json,"      ""rank"": -2,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"
				Print #json,"    {"
				Print #json,"      ""id"": 35381828,"
				Print #json,"      ""parentId"": 35350394,"
				Print #json,"      ""type"": ""number"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""name"": ""Level"","
				If val(right(values(i),2)) = 0 Then
					Print #json,"      ""value"": """","
				Else
					Print #json,"      ""value"": " & val(right(values(i),2)) & ","
				End If
				Print #json,"      ""rank"": -1,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"
								
 			Case "Morale":
				Print #json,"    {"
				Print #json,"      ""id"": 35398845,"
				Print #json,"      ""parentId"": 35350386,"
				Print #json,"      ""type"": ""number"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""name"": ""Morale"","
				Print #json,"      ""value"": " & values(i) & ","
				Print #json,"      ""rank"": 89,"
				Print #json,"      ""message"" : ""Morale Check: {2d6 <= morale}"","
				Print #json,"      ""characterId"": 673402"
				Print #json,"    },"
 			   		
    		Case "Lair Treasure Type":
				temp = 0 ' Do nothing

			Case "Carried Treasure Type":
				temp = 0 ' Do nothing
			
			Case "Intelligence":
				temp = 0 ' Do nothing

			Case "Alignment":
				temp = 0 ' Do nothing
    
			Case "XP":
				Print #json,"    {"
				Print #json,"      ""id"": 35506173,"
				Print #json,"      ""parentId"": 35350386,"
				Print #json,"      ""type"": ""number"","
				Print #json,"      ""data"": null,"
				Print #json,"      ""name"": ""Special XP Value"","
				Print #json,"      ""value"": " & values(i) & ","
				Print #json,"      ""rank"": 115,"
				Print #json,"      ""characterId"": 673402"
				Print #json,"    }"

			Case "Rule Book":
				temp = 0 ' Do nothing
			
			Case "Page":
				temp = 0 ' Do nothing
			
			Case "Picture":
				temp = 0 ' Do nothing
						
    		Case Else

	    	If i = klen-1 Then
	    		'Don't include comma after last entry
	    		Print #json, keyValLastEntry
	    	Else
	    		If i = lastValidLine Then
	    			Print #json, keyValLastEntry
	    		Else
	    			Print #json, keyValString
	    		End If
	    		
	    	End If
	    	
	    	End Select
    	Next i
    	
	End If

	' Close file 
	Print #json, "  ],"
	Print #json, "  ""private"": false,"
	Print #json, "  ""type"": ""tableplop-character-v2"" "
	Print #json, "}"
	Close #json

Next line
 
 
Close #csv          

End Sub
